<?php

namespace App\Docs\Swagger\Books;

/**
 * @OA\Get(
 *     path="/api/v1/books/{id}",
 *     tags={"Books"},
 *     summary="取得指定UUID的書本資料",
 *     description="只能查詢屬於自己的書本資料",
 *     security={
 *         {
 *             "Authorization": {}
 *         }
 *     },
 *     @OA\Parameter(
 *         name="id",
 *         description="UUID編號",
 *         required=true,
 *         in="path",
 *         @OA\Schema(
 *             type="string",
 *             example="fd824506-aa7f-4b61-987b-18a626a2cceb",
 *         )
 *     ),
 *     @OA\Response(
 *         response=200,
 *         description="請求已成功，請求所希望的回應頭或資料體將隨此回應返回",
 *         @OA\MediaType(
 *             mediaType="application\json",
 *             @OA\Schema(
 *                 @OA\Property(
 *                     property="data",
 *                     type="array",
 *                     description="每筆資料內容",
 *                     @OA\Items(
 *                         @OA\Property(
 *                             property="id",
 *                             type="string",
 *                             description="UUID編號",
 *                             example="fd824506-aa7f-4b61-987b-18a626a2cceb",
 *                         ),
 *                         @OA\Property(
 *                             property="title",
 *                             type="string",
 *                             description="標題",
 *                             example="理財通!!",
 *                         ),
 *                         @OA\Property(
 *                             property="author",
 *                             type="string",
 *                             description="作者",
 *                             example="阿囉哈",
 *                         ),
 *                         @OA\Property(
 *                             property="published_at",
 *                             type="string|null",
 *                             description="發布時間",
 *                             example="2023-07-04 23:44:37",
 *                         ),
 *                         @OA\Property(
 *                             property="category",
 *                             type="string",
 *                             description="分類",
 *                             example="阿囉哈",
 *                             enum={"投資理財", "文創手作", "心靈雞湯", "程式語言"},
 *                         ),
 *                         @OA\Property(
 *                             property="price",
 *                             type="number",
 *                             format="integer",
 *                             description="價格",
 *                             example=3
 *                         ),
 *                         @OA\Property(
 *                             property="quantity",
 *                             type="number",
 *                             format="integer",
 *                             description="數量",
 *                             example=3
 *                         ),
 *                         @OA\Property(
 *                             property="images",
 *                             type="array",
 *                             description="圖檔資料內容",
 *                             @OA\Items(
 *                                 @OA\Property(
 *                                     property="name",
 *                                     type="string",
 *                                     description="圖片名稱",
 *                                     example="Sunshine",
 *                                 ),
 *                                 @OA\Property(
 *                                     property="path",
 *                                     type="string",
 *                                     description="圖片路徑",
 *                                     example="https://images.unsplash.com/photo-1536484049453-85de4ea3db6a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1021&q=80",
 *                                 ),
 *                             )
 *                         )
 *                     ),
 *                 ),
 *             )
 *         )
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="需要授權以回應請求"
 *     ),
 *     @OA\Response(
 *         response=403,
 *         description="用戶端並無訪問權限，例如未被授權，所以伺服器拒絕給予應有的回應"
 *     ),
 *     @OA\Response(
 *         response=404,
 *         description="請求失敗，請求所希望得到的資源未被在伺服器上發現，但允許使用者的後續請求。"
 *     ),
 * )
 */
class Show { }