<?php

namespace App\Docs\Swagger\Books;

/**
 * @OA\Post(
 *     path="/api/v1/books",
 *     tags={"Books"},
 *     summary="上架書籍",
 *     description="上架的書籍只有自己能看的到, 當然也只有自己可以進行修改、 刪除",
 *     security={
 *         {
 *             "Authorization": {}
 *         }
 *     },
 *     @OA\Parameter(
 *         name="title",
 *         description="標題",
 *         required=true,
 *         in="query",
 *         @OA\Schema(
 *             type="string",
 *             example="標題!!",
 *         )
 *     ),
 *     @OA\Parameter(
 *         name="author",
 *         description="作者",
 *         required=true,
 *         in="query",
 *         @OA\Schema(
 *             type="string",
 *             example="作者",
 *         )
 *     ),
 *     @OA\Parameter(
 *         name="published_at",
 *         description="發佈時間",
 *         in="query",
 *         @OA\Schema(
 *             type="string",
 *             format="date-time",
 *             example="2023-07-04 23:44:37",
 *         )
 *     ),
 *     @OA\Parameter(
 *         name="category",
 *         description="類別",
 *         required=true,
 *         in="query",
 *         @OA\Schema(
 *             type="string",
 *             example="投資理財",
 *             enum={"投資理財", "文創手作", "心靈雞湯", "程式語言"},
 *         )
 *     ),
 *     @OA\Parameter(
 *         name="price",
 *         description="價格",
 *         required=true,
 *         in="query",
 *         @OA\Schema(
 *             type="integer",
 *             example="100",
 *         )
 *     ),
 *     @OA\Parameter(
 *         name="quantity",
 *         description="數量",
 *         required=true,
 *         in="query",
 *         @OA\Schema(
 *             type="integer",
 *             example="999",
 *         )
 *     ),
 *     @OA\Parameter(
 *         name="images[name]",
 *         description="圖片名稱",
 *         required=true,
 *         in="query",
 *         @OA\Schema(
 *             type="string",
 *             example="Sunshine",
 *         )
 *     ),
 *     @OA\Parameter(
 *         name="images[path]",
 *         description="圖片網址路徑",
 *         required=true,
 *         in="query",
 *         @OA\Schema(
 *             type="string",
 *             example="https://images.unsplash.com/photo-1536484049453-85de4ea3db6a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1021&q=80",
 *         )
 *     ),
 *     @OA\Response(
 *         response=201,
 *         description="請求已經被實現，而且有一個新的資源已經依據請求的需要而建立。"
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="需要授權以回應請求"
 *     ),
 *     @OA\Response(
 *         response=403,
 *         description="用戶端並無訪問權限，例如未被授權，所以伺服器拒絕給予應有的回應"
 *     ),
 *     @OA\Response(
 *         response=422,
 *         description="請求正確，但是由於含有格式錯誤，無法回應。"
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="通用錯誤訊息，伺服器遇到了一個未曾預料的狀況，導致了它無法完成對請求的處理。"
 *     ),
 * )
 */
class Store { }